[package]
name = "b2-galaga"
description = "Rust port of Bryan's Galaga port."
version = "0.1.0"
authors = ["Luqman Aden <me@luqman.ca>"]

[dependencies]
ggez = "0.5"
rand = "0.7"
specs = "0.15"
specs-derive = "0.4"
